version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: oopsie_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog
    container_name: oopsie_mailhog
    ports:
      - '1025:1025' # SMTP server
      - '8025:8025' # Web interface
    healthcheck:
      test: ['CMD', 'nc', '-z', 'localhost', '1025']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
